### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by princess-entrapta** [princess-entrapta/ribbit#1]
- [x]  Serveur backend up and running, with docker compose for local run
- [x] POST /post => creates a post in a redis db
- [x] GET /post/:post_id => returns post
- [x] Posts are markdown-compiled.
- [x] GET /search?q=keyword => Returns paginated search (see cooking website)

**Comment by libre-diane** [comment]
Completed as commit e9f05289b1b021d5f977dbd9be9ecb5a0d0428df
